version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Detroit"
    open-pull-requests-limit: 10
    reviewers:
      - "ColDog5044"
    assignees:
      - "ColDog5044"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for core dependencies
      - dependency-name: "tkinter"
        update-types: ["version-update:semver-major"]
      - dependency-name: "wakeonlan"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "ColDog5044"
    assignees:
      - "ColDog5044"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
